import { createActions } from "reduxsauce";

const { Types, Creators } = createActions({
  logout:[],
  login: ["formLogin","handleOpen"],
  loginSuccess: ["data"],
  loginError: [],
  getListUsers: ["page", "filter", "size"],
  getListUsersSuccess: ["data"],
  getListUsersError: [],
  deleteUser: ["userId", "handleClose"],
  deleteUserSuccess: [],
  deleteUserError: [],
  addEditUser: ["user", "handleClose"],
  addEditUserSuccess: [],
  addEditUserError: [],
});

const { 
  LOGOUT,
  LOGIN, 
  LOGIN_SUCCESS, 
  LOGIN_ERROR,
  GET_LIST_USERS,
  GET_LIST_USERS_SUCCESS,
  GET_LIST_USERS_ERROR,
  DELETE_USER,
  DELETE_USER_SUCCESS,
  DELETE_USER_ERROR,
  ADD_EDIT_USER,
  ADD_EDIT_USER_SUCCESS,
  ADD_EDIT_USER_ERROR,
} = Types;
const { 
  logout,
  login, 
  loginSuccess, 
  loginError,
  getListUsers,
  getListUsersSuccess,
  getListUsersError,
  deleteUser,
  deleteUserSuccess,
  deleteUserError,
  addEditUser,
  addEditUserSuccess,
  addEditUserError,
} = Creators;

export {
  LOGOUT,
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  logout,
  login,
  loginSuccess,
  loginError,
  GET_LIST_USERS,
  GET_LIST_USERS_SUCCESS,
  GET_LIST_USERS_ERROR,
  DELETE_USER,
  DELETE_USER_SUCCESS,
  DELETE_USER_ERROR,
  ADD_EDIT_USER,
  ADD_EDIT_USER_SUCCESS,
  ADD_EDIT_USER_ERROR,
  getListUsers,
  getListUsersSuccess,
  getListUsersError,
  deleteUser,
  deleteUserSuccess,
  deleteUserError,
  addEditUser,
  addEditUserSuccess,
  addEditUserError,
};
